// Generated by gencpp from file my_summit_localization/MyServiceMsg.msg
// DO NOT EDIT!


#ifndef MY_SUMMIT_LOCALIZATION_MESSAGE_MYSERVICEMSG_H
#define MY_SUMMIT_LOCALIZATION_MESSAGE_MYSERVICEMSG_H

#include <ros/service_traits.h>


#include <my_summit_localization/MyServiceMsgRequest.h>
#include <my_summit_localization/MyServiceMsgResponse.h>


namespace my_summit_localization
{

struct MyServiceMsg
{

typedef MyServiceMsgRequest Request;
typedef MyServiceMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MyServiceMsg
} // namespace my_summit_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_summit_localization::MyServiceMsg > {
  static const char* value()
  {
    return "920ca5ca095e1b5230fc32da338a974c";
  }

  static const char* value(const ::my_summit_localization::MyServiceMsg&) { return value(); }
};

template<>
struct DataType< ::my_summit_localization::MyServiceMsg > {
  static const char* value()
  {
    return "my_summit_localization/MyServiceMsg";
  }

  static const char* value(const ::my_summit_localization::MyServiceMsg&) { return value(); }
};


// service_traits::MD5Sum< ::my_summit_localization::MyServiceMsgRequest> should match
// service_traits::MD5Sum< ::my_summit_localization::MyServiceMsg >
template<>
struct MD5Sum< ::my_summit_localization::MyServiceMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_summit_localization::MyServiceMsg >::value();
  }
  static const char* value(const ::my_summit_localization::MyServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_summit_localization::MyServiceMsgRequest> should match
// service_traits::DataType< ::my_summit_localization::MyServiceMsg >
template<>
struct DataType< ::my_summit_localization::MyServiceMsgRequest>
{
  static const char* value()
  {
    return DataType< ::my_summit_localization::MyServiceMsg >::value();
  }
  static const char* value(const ::my_summit_localization::MyServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_summit_localization::MyServiceMsgResponse> should match
// service_traits::MD5Sum< ::my_summit_localization::MyServiceMsg >
template<>
struct MD5Sum< ::my_summit_localization::MyServiceMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_summit_localization::MyServiceMsg >::value();
  }
  static const char* value(const ::my_summit_localization::MyServiceMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_summit_localization::MyServiceMsgResponse> should match
// service_traits::DataType< ::my_summit_localization::MyServiceMsg >
template<>
struct DataType< ::my_summit_localization::MyServiceMsgResponse>
{
  static const char* value()
  {
    return DataType< ::my_summit_localization::MyServiceMsg >::value();
  }
  static const char* value(const ::my_summit_localization::MyServiceMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SUMMIT_LOCALIZATION_MESSAGE_MYSERVICEMSG_H
