(cl:in-package marti_dbw_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          PRESENT-VAL
          PRESENT
          ROBOTIC_MODE-VAL
          ROBOTIC_MODE
          STEERING_COMMAND-VAL
          STEERING_COMMAND
          STEERING_MEASURE-VAL
          STEERING_MEASURE
          THROTTLE_COMMAND-VAL
          THROTTLE_COMMAND
          THROTTLE_MEASURE-VAL
          THROTTLE_MEASURE
          BRAKE_COMMAND-VAL
          BRAKE_COMMAND
          BRAKE_MEASURE-VAL
          BRAKE_MEASURE
          ESTOP_COMMAND-VAL
          ESTOP_COMMAND
          ESTOP_MEASURE-VAL
          ESTOP_MEASURE
          ERROR_STEERING-VAL
          ERROR_STEERING
          ERROR_THROTTLE-VAL
          ERROR_THROTTLE
          ERROR_BRAKE-VAL
          ERROR_BRAKE
          ERROR_OTHER-VAL
          ERROR_OTHER
))