// Generated by gencpp from file my_summit_localization/MyServiceMsgRequest.msg
// DO NOT EDIT!


#ifndef MY_SUMMIT_LOCALIZATION_MESSAGE_MYSERVICEMSGREQUEST_H
#define MY_SUMMIT_LOCALIZATION_MESSAGE_MYSERVICEMSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_summit_localization
{
template <class ContainerAllocator>
struct MyServiceMsgRequest_
{
  typedef MyServiceMsgRequest_<ContainerAllocator> Type;

  MyServiceMsgRequest_()
    : label()  {
    }
  MyServiceMsgRequest_(const ContainerAllocator& _alloc)
    : label(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;





  typedef boost::shared_ptr< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MyServiceMsgRequest_

typedef ::my_summit_localization::MyServiceMsgRequest_<std::allocator<void> > MyServiceMsgRequest;

typedef boost::shared_ptr< ::my_summit_localization::MyServiceMsgRequest > MyServiceMsgRequestPtr;
typedef boost::shared_ptr< ::my_summit_localization::MyServiceMsgRequest const> MyServiceMsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator1> & lhs, const ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator1> & lhs, const ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_summit_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea23f97416b04c6151d2b576c0665ac1";
  }

  static const char* value(const ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea23f97416b04c61ULL;
  static const uint64_t static_value2 = 0x51d2b576c0665ac1ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_summit_localization/MyServiceMsgRequest";
  }

  static const char* value(const ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request\n"
"string label\n"
;
  }

  static const char* value(const ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyServiceMsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_summit_localization::MyServiceMsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SUMMIT_LOCALIZATION_MESSAGE_MYSERVICEMSGREQUEST_H
