# CMake generated Testfile for 
# Source directory: /home/khoa/catkin_ws/src/open_street_map/osm_cartography
# Build directory: /home/khoa/catkin_ws/build_isolated/osm_cartography
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_osm_cartography_nosetests_tests.test_geo_map.py "/home/khoa/catkin_ws/build_isolated/osm_cartography/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/khoa/catkin_ws/build_isolated/osm_cartography/test_results/osm_cartography/nosetests-tests.test_geo_map.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/khoa/catkin_ws/build_isolated/osm_cartography/test_results/osm_cartography" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/khoa/catkin_ws/src/open_street_map/osm_cartography/tests/test_geo_map.py --with-xunit --xunit-file=/home/khoa/catkin_ws/build_isolated/osm_cartography/test_results/osm_cartography/nosetests-tests.test_geo_map.py.xml")
add_test(_ctest_osm_cartography_nosetests_tests.test_xml_map.py "/home/khoa/catkin_ws/build_isolated/osm_cartography/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/khoa/catkin_ws/build_isolated/osm_cartography/test_results/osm_cartography/nosetests-tests.test_xml_map.py.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/khoa/catkin_ws/build_isolated/osm_cartography/test_results/osm_cartography" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/khoa/catkin_ws/src/open_street_map/osm_cartography/tests/test_xml_map.py --with-xunit --xunit-file=/home/khoa/catkin_ws/build_isolated/osm_cartography/test_results/osm_cartography/nosetests-tests.test_xml_map.py.xml")
add_test(_ctest_osm_cartography_roslaunch-check_launch "/home/khoa/catkin_ws/build_isolated/osm_cartography/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/khoa/catkin_ws/build_isolated/osm_cartography/test_results/osm_cartography/roslaunch-check_launch.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/khoa/catkin_ws/build_isolated/osm_cartography/test_results/osm_cartography" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o \"/home/khoa/catkin_ws/build_isolated/osm_cartography/test_results/osm_cartography/roslaunch-check_launch.xml\" \"/home/khoa/catkin_ws/src/open_street_map/osm_cartography/launch\" ")
subdirs("gtest")
