set(_CATKIN_CURRENT_PACKAGE "my_summit_path_planning")
set(my_summit_path_planning_VERSION "0.0.0")
set(my_summit_path_planning_MAINTAINER "user <user@todo.todo>")
set(my_summit_path_planning_PACKAGE_FORMAT "1")
set(my_summit_path_planning_BUILD_DEPENDS )
set(my_summit_path_planning_BUILD_EXPORT_DEPENDS )
set(my_summit_path_planning_BUILDTOOL_DEPENDS "catkin")
set(my_summit_path_planning_BUILDTOOL_EXPORT_DEPENDS )
set(my_summit_path_planning_EXEC_DEPENDS )
set(my_summit_path_planning_RUN_DEPENDS )
set(my_summit_path_planning_TEST_DEPENDS )
set(my_summit_path_planning_DOC_DEPENDS )
set(my_summit_path_planning_URL_WEBSITE "")
set(my_summit_path_planning_URL_BUGTRACKER "")
set(my_summit_path_planning_URL_REPOSITORY "")
set(my_summit_path_planning_DEPRECATED "")