; Auto-generated. Do not edit!


(cl:in-package swri_roscpp-msg)


;//! \htmlinclude TestTopicServiceResponse.msg.html

(cl:defclass <TestTopicServiceResponse> (roslisp-msg-protocol:ros-message)
  ((srv_header
    :reader srv_header
    :initarg :srv_header
    :type marti_common_msgs-msg:ServiceHeader
    :initform (cl:make-instance 'marti_common_msgs-msg:ServiceHeader))
   (response_value
    :reader response_value
    :initarg :response_value
    :type cl:integer
    :initform 0))
)

(cl:defclass TestTopicServiceResponse (<TestTopicServiceResponse>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TestTopicServiceResponse>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TestTopicServiceResponse)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name swri_roscpp-msg:<TestTopicServiceResponse> is deprecated: use swri_roscpp-msg:TestTopicServiceResponse instead.")))

(cl:ensure-generic-function 'srv_header-val :lambda-list '(m))
(cl:defmethod srv_header-val ((m <TestTopicServiceResponse>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader swri_roscpp-msg:srv_header-val is deprecated.  Use swri_roscpp-msg:srv_header instead.")
  (srv_header m))

(cl:ensure-generic-function 'response_value-val :lambda-list '(m))
(cl:defmethod response_value-val ((m <TestTopicServiceResponse>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader swri_roscpp-msg:response_value-val is deprecated.  Use swri_roscpp-msg:response_value instead.")
  (response_value m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TestTopicServiceResponse>) ostream)
  "Serializes a message object of type '<TestTopicServiceResponse>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'srv_header) ostream)
  (cl:let* ((signed (cl:slot-value msg 'response_value)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TestTopicServiceResponse>) istream)
  "Deserializes a message object of type '<TestTopicServiceResponse>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'srv_header) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'response_value) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TestTopicServiceResponse>)))
  "Returns string type for a message object of type '<TestTopicServiceResponse>"
  "swri_roscpp/TestTopicServiceResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TestTopicServiceResponse)))
  "Returns string type for a message object of type 'TestTopicServiceResponse"
  "swri_roscpp/TestTopicServiceResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TestTopicServiceResponse>)))
  "Returns md5sum for a message object of type '<TestTopicServiceResponse>"
  "ffa572c724c22095570f217a11ef9386")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TestTopicServiceResponse)))
  "Returns md5sum for a message object of type 'TestTopicServiceResponse"
  "ffa572c724c22095570f217a11ef9386")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TestTopicServiceResponse>)))
  "Returns full string definition for message of type '<TestTopicServiceResponse>"
  (cl:format cl:nil "# Test message used only for swri_roscpp unit tests~%# Messages for TopicServices would normally be generated by the add_topic_service_files CMake macro~%marti_common_msgs/ServiceHeader srv_header~%int32 response_value~%~%================================================================================~%MSG: marti_common_msgs/ServiceHeader~%# This message contains all of the data filled in automatically by the service system~%# It is required in each request and response message to be named srv_header~%time stamp~%uint32 sequence~%string sender~%bool result # Used to indicate if the service request was successful or not~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TestTopicServiceResponse)))
  "Returns full string definition for message of type 'TestTopicServiceResponse"
  (cl:format cl:nil "# Test message used only for swri_roscpp unit tests~%# Messages for TopicServices would normally be generated by the add_topic_service_files CMake macro~%marti_common_msgs/ServiceHeader srv_header~%int32 response_value~%~%================================================================================~%MSG: marti_common_msgs/ServiceHeader~%# This message contains all of the data filled in automatically by the service system~%# It is required in each request and response message to be named srv_header~%time stamp~%uint32 sequence~%string sender~%bool result # Used to indicate if the service request was successful or not~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TestTopicServiceResponse>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'srv_header))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TestTopicServiceResponse>))
  "Converts a ROS message object to a list"
  (cl:list 'TestTopicServiceResponse
    (cl:cons ':srv_header (srv_header msg))
    (cl:cons ':response_value (response_value msg))
))
