; Auto-generated. Do not edit!


(cl:in-package swri_roscpp-msg)


;//! \htmlinclude TestTopicServiceRequest.msg.html

(cl:defclass <TestTopicServiceRequest> (roslisp-msg-protocol:ros-message)
  ((srv_header
    :reader srv_header
    :initarg :srv_header
    :type marti_common_msgs-msg:ServiceHeader
    :initform (cl:make-instance 'marti_common_msgs-msg:ServiceHeader))
   (request_value
    :reader request_value
    :initarg :request_value
    :type cl:integer
    :initform 0))
)

(cl:defclass TestTopicServiceRequest (<TestTopicServiceRequest>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TestTopicServiceRequest>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TestTopicServiceRequest)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name swri_roscpp-msg:<TestTopicServiceRequest> is deprecated: use swri_roscpp-msg:TestTopicServiceRequest instead.")))

(cl:ensure-generic-function 'srv_header-val :lambda-list '(m))
(cl:defmethod srv_header-val ((m <TestTopicServiceRequest>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader swri_roscpp-msg:srv_header-val is deprecated.  Use swri_roscpp-msg:srv_header instead.")
  (srv_header m))

(cl:ensure-generic-function 'request_value-val :lambda-list '(m))
(cl:defmethod request_value-val ((m <TestTopicServiceRequest>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader swri_roscpp-msg:request_value-val is deprecated.  Use swri_roscpp-msg:request_value instead.")
  (request_value m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TestTopicServiceRequest>) ostream)
  "Serializes a message object of type '<TestTopicServiceRequest>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'srv_header) ostream)
  (cl:let* ((signed (cl:slot-value msg 'request_value)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TestTopicServiceRequest>) istream)
  "Deserializes a message object of type '<TestTopicServiceRequest>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'srv_header) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'request_value) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TestTopicServiceRequest>)))
  "Returns string type for a message object of type '<TestTopicServiceRequest>"
  "swri_roscpp/TestTopicServiceRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TestTopicServiceRequest)))
  "Returns string type for a message object of type 'TestTopicServiceRequest"
  "swri_roscpp/TestTopicServiceRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TestTopicServiceRequest>)))
  "Returns md5sum for a message object of type '<TestTopicServiceRequest>"
  "62086d0669b9627ef32b14cac1955c4c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TestTopicServiceRequest)))
  "Returns md5sum for a message object of type 'TestTopicServiceRequest"
  "62086d0669b9627ef32b14cac1955c4c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TestTopicServiceRequest>)))
  "Returns full string definition for message of type '<TestTopicServiceRequest>"
  (cl:format cl:nil "# Test message used only for swri_roscpp unit tests~%# Messages for TopicServices would normally be generated by the add_topic_service_files CMake macro~%marti_common_msgs/ServiceHeader srv_header~%int32 request_value~%~%================================================================================~%MSG: marti_common_msgs/ServiceHeader~%# This message contains all of the data filled in automatically by the service system~%# It is required in each request and response message to be named srv_header~%time stamp~%uint32 sequence~%string sender~%bool result # Used to indicate if the service request was successful or not~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TestTopicServiceRequest)))
  "Returns full string definition for message of type 'TestTopicServiceRequest"
  (cl:format cl:nil "# Test message used only for swri_roscpp unit tests~%# Messages for TopicServices would normally be generated by the add_topic_service_files CMake macro~%marti_common_msgs/ServiceHeader srv_header~%int32 request_value~%~%================================================================================~%MSG: marti_common_msgs/ServiceHeader~%# This message contains all of the data filled in automatically by the service system~%# It is required in each request and response message to be named srv_header~%time stamp~%uint32 sequence~%string sender~%bool result # Used to indicate if the service request was successful or not~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TestTopicServiceRequest>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'srv_header))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TestTopicServiceRequest>))
  "Converts a ROS message object to a list"
  (cl:list 'TestTopicServiceRequest
    (cl:cons ':srv_header (srv_header msg))
    (cl:cons ':request_value (request_value msg))
))
