set(_CATKIN_CURRENT_PACKAGE "marti_dbw_msgs")
set(marti_dbw_msgs_VERSION "0.10.0")
set(marti_dbw_msgs_MAINTAINER "Matthew Bries <mbries@swri.org>")
set(marti_dbw_msgs_PACKAGE_FORMAT "2")
set(marti_dbw_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(marti_dbw_msgs_BUILD_EXPORT_DEPENDS "std_msgs")
set(marti_dbw_msgs_BUILDTOOL_DEPENDS "catkin")
set(marti_dbw_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(marti_dbw_msgs_EXEC_DEPENDS "message_runtime" "std_msgs")
set(marti_dbw_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(marti_dbw_msgs_TEST_DEPENDS )
set(marti_dbw_msgs_DOC_DEPENDS )
set(marti_dbw_msgs_URL_WEBSITE "")
set(marti_dbw_msgs_URL_BUGTRACKER "")
set(marti_dbw_msgs_URL_REPOSITORY "https://github.com/swri-robotics/marti_messages")
set(marti_dbw_msgs_DEPRECATED "")