set(_CATKIN_CURRENT_PACKAGE "my_summit_localization")
set(my_summit_localization_VERSION "0.0.0")
set(my_summit_localization_MAINTAINER "user <user@todo.todo>")
set(my_summit_localization_PACKAGE_FORMAT "1")
set(my_summit_localization_BUILD_DEPENDS "rospy" "message_generation")
set(my_summit_localization_BUILD_EXPORT_DEPENDS "rospy" "message_runtime")
set(my_summit_localization_BUILDTOOL_DEPENDS "catkin")
set(my_summit_localization_BUILDTOOL_EXPORT_DEPENDS )
set(my_summit_localization_EXEC_DEPENDS "rospy" "message_runtime")
set(my_summit_localization_RUN_DEPENDS "rospy" "message_runtime")
set(my_summit_localization_TEST_DEPENDS )
set(my_summit_localization_DOC_DEPENDS )
set(my_summit_localization_URL_WEBSITE "")
set(my_summit_localization_URL_BUGTRACKER "")
set(my_summit_localization_URL_REPOSITORY "")
set(my_summit_localization_DEPRECATED "")